---
title: "PCA"
author: "Pei Hsin Lin"
date: "7/27/2022"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(shape)
#library(brainGraph)
library(parallel)
library(dplyr)
library(rdd)

library(graphsim) # need to compuate laplacean matrix
library(igraph) # need to compuate laplacean matrix

networkcal<-function(tmpmat, num.cores=16, mcmethod='BY'){
    pmat=do.call(cbind, mclapply(1:ncol(tmpmat),function(k)apply(tmpmat, 2, function(xx)cor.test(xx, tmpmat[,k])$p.value), mc.cores=num.cores))
  lmat=matrix(0, ncol(tmpmat), ncol(tmpmat))
  lmat[lower.tri(lmat)]<-as.numeric(p.adjust(pmat[lower.tri(pmat)], method=mcmethod)<0.05)
  lmat=lmat+t(lmat)
  return(lmat)
}
```



# Data processing

* Compute sliding-window-based functional connectivity: read power parcellation (264 locations), we may exclude cerebellum later

* use task-activation removed matrix reasoning fMRI data

```{r, eval=FALSE}
filelist = list.files(
  '/Volumes/promise_p/CRRANN/derivatives/Parcelled_TS/power_ts/matreas_residual',
  pattern='.txt', full.name=TRUE)

matreas=data.frame(Sub.ID = as.numeric(substr(filelist,83,86)),
                   filelist=filelist) %>%
  left_join(., read.csv('/Users/seonjoolee/Library/CloudStorage/GoogleDrive-seonjoo.lee@nyspi.columbia.edu/My\ Drive/Collaboration/Yaakov/data/RN_CR_Data_Part_1_ver_2.6.csv')[,c(1:10,93:96)]) %>%
  left_join(., read.csv('/Users/seonjoolee/Library/CloudStorage/GoogleDrive-seonjoo.lee@nyspi.columbia.edu/My\ Drive/Collaboration/Yaakov/data/RN_CR_Data_Part_2_ver_2.6.csv')) 

ts = mclapply(matreas$filelist,
            function(str)read.table(str), mc.cores=16)

sfc = lapply(ts, function(obj)networkcal(obj, mcmethod='bonferroni'))
save(ts, matreas, sfc, file='../Data/CRRANN_matrisreasoning_residual_n293.Rdat')
```

## Static FC {.tabset}

```{r}
load('/Users/lin/Desktop/CRRANN_matrisreasoning_residual_n293.Rdat')



# convert graph Laplacian

sfc.laplacian=mclapply(sfc, 
                       function(obj)make_laplacian_adjmat(obj, directed = FALSE), mc.cores=16)

# normalized laplacian
sfc.laplacian.norm=mclapply(sfc.laplacian, 
                       function(obj)obj/sum(diag(obj)), mc.cores=16)

# Nadaraya–Watson estimator 

# since laplacian is symmetric, only take the lower triangular matrix

sfc.laplacian.tmpmat=do.call(rbind, lapply(sfc.laplacian.norm,function(xx)xx[lower.tri(xx, diag=TRUE)] ))

sfc.laplacian.tmpmat.c=scale(sfc.laplacian.tmpmat)
```

##bandwidth selection
```{r}

   
CV_A<-function(bw, fold, var, df){
            if(!is.numeric(df[[var]]))
            sapply(bw,function(x) {
              
            sapply(fold,function(y)
           {
            k=length(1:10)
            set.seed(2022)
            sample.size=nrow(df)
            a=matrix(NA,length(2:15),length(1:10))
            cv_lab = sample(sample.size,sample.size,replace=F) %% k
            ageeval=seq(min(df[[var]]),max(df[[var]]),1)
            w_val = which(cv_lab==(y-1))
            tr = df[-w_val,]
            val= df[w_val,]
            tmpkmat<-do.call(cbind,
                               lapply(ageeval,function(ss)kernelwts(tr[[var]],ss,x, kernel = "tricube")))
            estimates<-(t(tmpkmat) %*% sfc.laplacian.tmpmat.c[-w_val,])
            resid<-((estimates[val[[var]]-(min(df[[var]]-1)),] - sfc.laplacian.tmpmat.c[w_val,]))
            a[x-1,y] = mean(resid*resid)
              
              })
              
            }) 
                else if(
                  
            is.numeric(df[[var]])){
            sapply(bw,function(x){
              
            sapply(fold,function(y)
                      {
             df$var = df[,var]
             k=length(1:10)
             set.seed(2022)
             sample.size=nrow(df)
             a=matrix(NA,length(2:15),length(1:10))
             df<-within(df , Unique_ID<- as.numeric(factor(paste(var))))
             seq1<-df %>%
             distinct(var) %>%
             pull(var) %>%
             as.numeric %>%
               sort
             cv_lab = sample(sample.size,sample.size,replace=F) %% k
             w_val = which(cv_lab==(y-1))
             tr = df[-w_val,]
             val= df[w_val,]
             tmpkmat<-do.call(cbind,
                               lapply(seq1,function(ss)kernelwts(tr[[var]],ss,x, kernel = "tricube")))
             estimates<-(t(tmpkmat) %*% sfc.laplacian.tmpmat.c[-w_val,])
             resid<-((estimates[val$Unique_ID,]- sfc.laplacian.tmpmat.c[w_val,]))
             a[x-1,y] = mean(resid*resid)
              
             })
             }) 
             }
             }
```

```{r}

cv1<-CV_A(2:15,1:10,"Age",matreas)
sumcv<-colSums(cv1)
plot(x=2:15, y=sumcv, type="b", lwd=3, col="blue", xlab="Smoothing bandwidth", ylab="CV MSE")
cv2<-CV_A(seq(4,13,0.5),1:5,"NPReasoning",matreas)
sumcv2<-colSums(cv2)
cv2_10<-CV_A(seq(4,13,0.5),1:10,"NPReasoning",matreas)
sumcv2_10<-colSums(cv2_10)

cv3<-CV_A(seq(4,13,0.5),1:10,"NPMemory",matreas)
sumcv3<-colSums(cv3)
cv4<-CV_A(seq(4,13,0.5),1:10,"NPVocab",matreas)
sumcv4<-colSums(cv4)
cv5<-CV_A(seq(4,13,0.5),1:5,"NPSpeed_attention",matreas)
sumcv5<-colSums(cv5)
cv5_10<-CV_A(seq(4,13,0.5),1:10,"NPSpeed_attention",matreas)
sumcv5_10<-colSums(cv5_10)
```

##PCA Visualization
### Age

```{r}
ageeval=seq(19,80,2)
bandwidth=13

# Kernel weight
plot(seq(20,80,0.1),
     kernelwts(seq(20,80,0.1), 50, bandwidth, kernel = "tricube"), type='l')


tmpkmat = do.call(cbind,
                  lapply(ageeval,
                         function(ss)kernelwts(matreas$Age, ss, bandwidth, kernel = "tricube")))


sfc.laplacian.tmpmat.c=scale(sfc.laplacian.tmpmat)
estimates = t(tmpkmat) %*% sfc.laplacian.tmpmat.c ## estimates at age 20,25,30,...,80.



n = nrow(sfc.laplacian.tmpmat.c)
sfc.laplacian.pca = eigen(sfc.laplacian.tmpmat.c %*% t(sfc.laplacian.tmpmat.c)/(n-1))

sfc.laplacian.pca.loading = diag(1/sqrt(sfc.laplacian.pca$values[1:(n-1)])) %*% t(sfc.laplacian.pca$vectors[,1:(n-1)]) %*% sfc.laplacian.tmpmat.c

## project estimates on the PCA
estimates.pc=sfc.laplacian.pca.loading[1:(n-1),] %*% t(estimates)

sfc.laplacian.pca.scores=sfc.laplacian.pca.loading[1:(n-1),] %*% t(sfc.laplacian.tmpmat.c)

indx=order(matreas$Age)


par(mfrow=c(2,2))
plot(sfc.laplacian.pca.scores[1,indx],sfc.laplacian.pca.scores[2,indx], 
     col=rainbow(80)[matreas$Age[indx]-18], pch=15 )
lines(estimates.pc[1,],estimates.pc[2,])

plot(estimates.pc[1,],estimates.pc[2,], type='l');points(estimates.pc[1,],estimates.pc[2,],col=rainbow(80)[ageeval-18], pch=15)


#PCA plot of the first two PC scores in Figure and include the Nadaraya–Watson estimator projected into the space of the first two PCs. Here the bandwidth has been chosen by cross-validation as bandwidth=13. A turning point around age 32 to 45. Maybe the example of the horseshoe effect, it happened when the distances  are large between data points.

plot(ageeval,estimates.pc[1,],type='l');points(ageeval,estimates.pc[1,],col=rainbow(80)[ageeval-18], pch=15)
plot(ageeval,estimates.pc[2,],type='l');points(ageeval,estimates.pc[2,],col=rainbow(80)[ageeval-18], pch=15)

```

###reasoning
```{r}
which(sumcv2_10==min(sumcv2_10))
4+(4*0.5)
#the best bandwidth for reasoning is 6

reasoning<-matreas %>%
distinct(NPReasoning) %>%
pull(NPReasoning) %>%
as.numeric %>%
sort

matreas1<-within(matreas , Unique_ID_R<- as.numeric(factor(paste(NPReasoning))))

bandwidth=6
```

```{r}
# Kernel weight
plot(reasoning,
     kernelwts(reasoning,mean(reasoning), bandwidth, kernel = "tricube"), type='l')


tmpkmat = do.call(cbind,
                  lapply(reasoning,
                         function(ss)kernelwts(matreas$NPReasoning,ss, bandwidth, kernel = "tricube")))

sfc.laplacian.tmpmat.c=scale(sfc.laplacian.tmpmat)
estimates = t(tmpkmat) %*% sfc.laplacian.tmpmat.c ## estimates at reasoning 

n = nrow(sfc.laplacian.tmpmat.c)
sfc.laplacian.pca = eigen(sfc.laplacian.tmpmat.c %*% t(sfc.laplacian.tmpmat.c)/(n-1))

sfc.laplacian.pca.loading = diag(1/sqrt(sfc.laplacian.pca$values[1:(n-1)])) %*% t(sfc.laplacian.pca$vectors[,1:(n-1)]) %*% sfc.laplacian.tmpmat.c

## project estimates on the PCA
estimates.pc=sfc.laplacian.pca.loading[1:(n-1),] %*% t(estimates)

sfc.laplacian.pca.scores=sfc.laplacian.pca.loading[1:(n-1),] %*% t(sfc.laplacian.tmpmat.c)

indxR=order(matreas$NPReasoning)
indxR2=sort(matreas1$Unique_ID_R)

par(mfrow=c(2,2))
plot(sfc.laplacian.pca.scores[1,indxR],sfc.laplacian.pca.scores[2,indxR], 
     col=rainbow(80)[indxR2], pch=15 )
lines(estimates.pc[1,],estimates.pc[2,])

#PCA plot of the first two PC scores in Figure and include the Nadaraya–Watson estimator projected into the space of the first two PCs. Here the bandwidth has been chosen by cross-validation as bandwidth=6. There are large distances between the first few and last few observations compared to the central observations.

plot(estimates.pc[1,],estimates.pc[2,],type='l');points(estimates.pc[1,],estimates.pc[2,],
                                                        col=rainbow(80), pch=15)

plot(reasoning,estimates.pc[1,],type='l');points(reasoning,estimates.pc[1,],col=rainbow(80), pch=15)

plot(reasoning,estimates.pc[2,],type='l');points(reasoning,estimates.pc[2,],col=rainbow(80), pch=15)


```

#NPMemory
```{r}
Memory<-matreas%>%
distinct(NPMemory) %>%
pull(NPMemory) %>%
as.numeric %>%
sort
matreas1<-within(matreas , Unique_ID_N<- as.numeric(factor(paste(NPMemory))))
which(sumcv3== min(sumcv3))
4+(10*0.5)
bandwidth=9
```

```{r}
tmpkmat = do.call(cbind,
                  lapply(Memory,
                         function(ss)kernelwts(matreas$NPMemory, ss, bandwidth, kernel = "tricube")))

sfc.laplacian.tmpmat.c=scale(sfc.laplacian.tmpmat)
estimates = t(tmpkmat) %*% sfc.laplacian.tmpmat.c ## estimates at reasoning 

n = nrow(sfc.laplacian.tmpmat.c)
sfc.laplacian.pca = eigen(sfc.laplacian.tmpmat.c %*% t(sfc.laplacian.tmpmat.c)/(n-1))

sfc.laplacian.pca.loading = diag(1/sqrt(sfc.laplacian.pca$values[1:(n-1)])) %*% t(sfc.laplacian.pca$vectors[,1:(n-1)]) %*% sfc.laplacian.tmpmat.c

## project estimates on the PCA
estimates.pc=sfc.laplacian.pca.loading[1:(n-1),] %*% t(estimates)

sfc.laplacian.pca.scores=sfc.laplacian.pca.loading[1:(n-1),] %*% t(sfc.laplacian.tmpmat.c)

indxM=order(matreas$NPMemory)
indxM2=sort(matreas1$Unique_ID_N)
indxR3=sort(order(Memory))

par(mfrow=c(2,2))
plot(sfc.laplacian.pca.scores[1,indxM],sfc.laplacian.pca.scores[2,indxM], 
     col=rainbow(80)[indxM2], pch=15 )
lines(estimates.pc[1,],estimates.pc[2,])

plot(estimates.pc[1,],estimates.pc[2,],type='l');points(estimates.pc[1,],estimates.pc[2,],
                                                        col=rainbow(80), pch=15)

#PCA plot of the first two PC scores in Figure and include the Nadaraya–Watson estimator projected into the space of the first two PCs. Here the bandwidth has been chosen by cross-validation as bandwidth=9. There are large distances between the first few observations compared to the central observations.

plot(Memory,estimates.pc[1,],type='l');points(Memory,estimates.pc[1,],col=rainbow(80), pch=15)

plot(Memory,estimates.pc[2,],type='l');points(Memory,estimates.pc[2,],col=rainbow(80), pch=15)





```

## NPVocab

```{r}
Vocab<-matreas%>%
distinct(NPVocab) %>%
pull(NPVocab) %>%
as.numeric %>%
sort

matreas1<-within(matreas , Unique_ID_V<- as.numeric(factor(paste(NPVocab))))

bandwidth=13

which(sumcv4== min(sumcv4))
4+(18*0.5)
```

```{r}
tmpkmat = do.call(cbind,
                  lapply(Vocab,
                         function(ss)kernelwts(matreas$NPVocab, ss, bandwidth, kernel = "tricube")))

sfc.laplacian.tmpmat.c=scale(sfc.laplacian.tmpmat)
estimates = t(tmpkmat) %*% sfc.laplacian.tmpmat.c ## estimates at reasoning 

n = nrow(sfc.laplacian.tmpmat.c)
sfc.laplacian.pca = eigen(sfc.laplacian.tmpmat.c %*% t(sfc.laplacian.tmpmat.c)/(n-1))

sfc.laplacian.pca.loading = diag(1/sqrt(sfc.laplacian.pca$values[1:(n-1)])) %*% t(sfc.laplacian.pca$vectors[,1:(n-1)]) %*% sfc.laplacian.tmpmat.c

## project estimates on the PCA
estimates.pc=sfc.laplacian.pca.loading[1:(n-1),] %*% t(estimates)

sfc.laplacian.pca.scores=sfc.laplacian.pca.loading[1:(n-1),] %*% t(sfc.laplacian.tmpmat.c)
indxV=order(matreas$NPVocab)
indxV2=sort(matreas1$Unique_ID_V)


par(mfrow=c(2,2))
plot(sfc.laplacian.pca.scores[1,indxV],sfc.laplacian.pca.scores[2,indxV], 
     col=rainbow(80)[indxV2], pch=15 )
lines(estimates.pc[1,],estimates.pc[2,])

#PCA plot of the first two PC scores in Figure and include the Nadaraya–Watson estimator projected into the space of the first two PCs. Here the bandwidth has been chosen by cross-validation as bandwidth=13. There are large distances between the first few observations compared to the central observations.

plot(estimates.pc[1,],estimates.pc[2,],type='l');points(estimates.pc[1,],estimates.pc[2,],
                                                        col=rainbow(80), pch=15)

plot(Vocab,estimates.pc[1,],type='l');points(Vocab,estimates.pc[1,],col=rainbow(80), pch=15)

plot(Vocab,estimates.pc[2,],type='l');points(Vocab,estimates.pc[2,],col=rainbow(80), pch=15)


```

##NPSpeed_attention

```{r}
Speed<-matreas%>%
distinct(NPSpeed_attention) %>%
pull(NPSpeed_attention) %>%
as.numeric %>%
sort
matreas1<-within(matreas , Unique_ID_S<- as.numeric(factor(paste(NPSpeed_attention))))
which(sumcv5_10== min(sumcv5_10))
4+(5*0.5)
bandwidth=6.5
```


```{r}

tmpkmat = do.call(cbind,
                  lapply(Speed,
                         function(ss)kernelwts(matreas$NPSpeed_attention, ss, bandwidth, kernel = "tricube")))

sfc.laplacian.tmpmat.c=scale(sfc.laplacian.tmpmat)
estimates = t(tmpkmat) %*% sfc.laplacian.tmpmat.c ## estimates at reasoning 

n = nrow(sfc.laplacian.tmpmat.c)
sfc.laplacian.pca = eigen(sfc.laplacian.tmpmat.c %*% t(sfc.laplacian.tmpmat.c)/(n-1))

sfc.laplacian.pca.loading = diag(1/sqrt(sfc.laplacian.pca$values[1:(n-1)])) %*% t(sfc.laplacian.pca$vectors[,1:(n-1)]) %*% sfc.laplacian.tmpmat.c

## project estimates on the PCA
estimates.pc=sfc.laplacian.pca.loading[1:(n-1),] %*% t(estimates)

sfc.laplacian.pca.scores=sfc.laplacian.pca.loading[1:(n-1),] %*% t(sfc.laplacian.tmpmat.c)

indxS=order(matreas$NPSpeed_attention)
indxS2=sort(matreas1$Unique_ID_S)


par(mfrow=c(2,2))
plot(sfc.laplacian.pca.scores[1,indxS],sfc.laplacian.pca.scores[2,indxS], 
     col=rainbow(80)[indxS2], pch=15 )
lines(estimates.pc[1,],estimates.pc[2,])

#PCA plot of the first two PC scores in Figure and include the Nadaraya–Watson estimator projected into the space of the first two PCs. Here the bandwidth has been chosen by cross-validation as bandwidth=6.5. There are large distances between the first observation compared to all the other observations.

plot(estimates.pc[1,],estimates.pc[2,],type='l');points(estimates.pc[1,],estimates.pc[2,],
                                                        col=rainbow(80), pch=15)

plot(Speed,estimates.pc[1,],type='l');points(Speed,estimates.pc[1,],col=rainbow(80), pch=15)

plot(Speed,estimates.pc[2,],type='l');points(Speed,estimates.pc[2,],col=rainbow(80), pch=15)


```
